name: practical_showcase_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  bloc: ^8.1.1
  bloc_concurrency: ^0.2.1
  cached_network_image: ^3.2.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  http: ^0.13.5
  jsonplaceholder_api:
    path: packages/jsonplaceholder_api
  jsonplaceholder_repository:
    path: packages/jsonplaceholder_repository
  meta: ^1.8.0
  online_jsonplaceholder_api:
    path: packages/online_jsonplaceholder_api
  stream_transform: ^2.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  network_image_mock: ^2.0.1

flutter:
  uses-material-design: true
